# Performing Calculations Using Vectors and Matrices 

## Introducing NumPy
The NumPy package provides essential functionality for scientific computing in Python. To use NumPy, you import it using ```import numpy as np```, allowing you to access the NumPy library through the common abbreviation ```np```. 

Python provides access to just one data type in any particular category. However, in scientific calculations, you often need better control over how data appears in memory, which means having more data types, something that ```numpy``` provides for you.

**E.G.** To define a scalar as a ```short``` (a 16-bit value), you could define it as ```myShort = np.short(yourScalar)```.

### Definitions
*scalar* - a single base data item, such as the number 2 shown by itself

*vector* - a one-dimensional array of scalars; it is access via a zero-based index

*matrix* - a two-or-more dimensional array of scalar

### Understanding Scalar and Vector Operations

#### Use the ```numpy array``` function to create a vector

In [3]:
import numpy as np

myVect = np.array([1, 2, 3, 4])
myVect

array([1, 2, 3, 4])

#### Use `np.arange(start, end, stepSize)` to create a vector

In [4]:
myVect = np.arange(1, 10, 2)
myVect

array([1, 3, 5, 7, 9])

#### Create a vector with a specific data type

In [6]:
myVect = np.array(np.int16([1, 2, 3, 4]))
myVect

array([1, 2, 3, 4], dtype=int16)

#### Create special vectors with `np.ones` and `np.zeros` 

In [38]:
myVect = np.ones(5, dtype=np.int16)
myVect

array([1, 1, 1, 1, 1], dtype=int16)

In [39]:
myVect = np.zeros(5, dtype=np.int16)
myVect

array([0, 0, 0, 0, 0], dtype=int16)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

#### Manipulating vectors
You can perform basic math functions on vectors as a whole, whcih makes this incredibly useful and less prone to errors that can occur when using programming constructs such as loops to perform the same task. 

In [21]:
myVect = np.array(np.int16([1, 2, 3, 4]))
myVect

array([1, 2, 3, 4], dtype=int16)

In [22]:
myVect = myVect + 1
myVect

array([2, 3, 4, 5], dtype=int16)

In [23]:
myVect = myVect - 2
myVect

array([0, 1, 2, 3], dtype=int16)

In [24]:
myVect = 2 ** myVect
myVect

array([1, 2, 4, 8], dtype=int16)

#### Performing logical and comparison tasks

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

a == b

array([False,  True, False,  True])

In [26]:
a < b

array([ True, False,  True, False])

#### Logical operations rely on special functions

In [27]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

np.logical_or(a, b)

array([ True,  True,  True, False])

In [28]:
np.logical_and(a, b)

array([ True, False, False, False])

In [29]:
np.logical_not(a)

array([False,  True, False,  True])

In [30]:
np.logical_xor(a, b)

array([False,  True,  True, False])

### Performing vector multiplication

In [31]:
myVect = np.array([1, 2, 3, 4])

myVect * myVect

array([ 1,  4,  9, 16])

#### The Dot Production
Unfortunately, an element-by-element multiplication can produce incorrect results when working with algorithms. In many cases, what you really need is a *dot product*, which is the sum of the products of two number sequences.

In [32]:
myVect.dot(myVect)

30

### Creating a Matrix

In [34]:
myMat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
myMat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Accessing Values

In [35]:
myMat[1, 1]

5

#### You can produce matrices  with any number of dimensions

In [36]:
myMat = np.array([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])
myMat

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
myMat[1, 1, 1]

8

#### Create special matrices with `np.ones` and `np.zeros`

In [40]:
myMat = np.ones((2,4), dtype=np.int16)
myMat

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [41]:
myMat = np.zeros((3,2), dtype=np.int16)
myMat

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

#### The `numpy.mat` function

In [42]:
myMat = np.mat([[1, 2, 3],
                [4, 5, 6],
                [5, 6, 7]])
myMat

matrix([[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]])

### Multiplying Matrices
#### Element-by-Element

In [43]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

a * b

array([[ 1,  4,  9],
       [16, 25, 36]])

#### Dot Product
Dot products work completely differently with matrices. The number of columns in matrix amust math the number of rows in matrix b.

In [44]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1, 2, 3],
              [3, 4, 5],
              [5, 6, 7]])

a.dot(b)

array([[22, 28, 34],
       [49, 64, 79]])

The matrix class makes multiplication simpler.

In [48]:
a = np.mat([[1, 2, 3],
              [4, 5, 6]])
b = np.mat([[1, 2, 3],
              [3, 4, 5],
              [5, 6, 7]])
a * b

matrix([[22, 28, 34],
        [49, 64, 79]])

### Defining Advanced Matrix Operations
#### The `np.reshape(x, y)` function

In [59]:
changeIt = np.array([1, 2, 3, 4, 5, 6, 7, 8])
changeIt

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
changeIt = changeIt.reshape(2, 4)
changeIt

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
changeIt.reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### Transpose Matrices

In [62]:
np.transpose(changeIt)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Creating Combinations the Right Way
### Distinguishing Permutations
#### Random Permutations

In [64]:
a = np.array([1, 2, 3])
np.random.permutation(a)

array([2, 3, 1])

#### Fetching All Permutations

In [65]:
from itertools import permutations

for p in permutations(a):
    print(p)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


### Shuffling Combinations
In some cases, you don't need an entire dataset; all you really need are a few of the members in combinations of a specific length.

In [68]:
from itertools import combinations
import random

a = np.array([1, 2, 3, 4])

for c in combinations(a, 2):
    print(c)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [69]:
pool = []

for c in combinations(a, 2):
    pool.append(c)
    
random.sample(pool, 3)

[(2, 3), (1, 3), (3, 4)]

### Facing Repititions
Repeated data can unfairly weight the output of an algorithm so that you get inaccurate results. Python makes it easy to remove certain types of repeated data.

In [72]:
a = np.array([1, 2, 3, 4, 5, 6, 6, 7, 7, 1, 2, 3])
b = np.array(list(set(a)))

b

array([1, 2, 3, 4, 5, 6, 7])

## Getting the Desired Results Using Recursion

*Recursion* is an elegant method of solving many computer problems that relies on the capability of a function to continue calling itself until it satisfies a particular condition. A recursive function does something, and then calls itself repeatedly until the task reaches a specific condition - but all those previous calls are still active. The calls unwind themselves one at a time until the first call finally ends with the correct answer.

In [78]:
def recursiveFactorial(n):
    print("Calculating recursiveFactorial({}) ...".format(n))
    if n == 1 or n == 0:
        print("\nEnd condition met.\n")
        return 1
    else:
        return n * recursiveFactorial(n-1)
    
print(recursiveFactorial(5))

Calculating recursiveFactorial(5) ...
Calculating recursiveFactorial(4) ...
Calculating recursiveFactorial(3) ...
Calculating recursiveFactorial(2) ...
Calculating recursiveFactorial(1) ...

End condition met.

120


### Eliminating Tail Call Recursion
a *tail call* occurs any time the recursion makes a call to the function as the last thing before it returns. Using a tail call forces Python to keep track of the individual call values until the recursion rewinds - each call consumes memory. 

With a little fancy programming, you can potentially eliminate tail calls from your recursive routines; however, the simplest approach to take when you want to eliminate recursion is to create an iterative alternative that performs the same task.

In [84]:
def iterativeFactorial(n):
    print("Calculating iterativeFactorial({})\n".format(n))
    result = 1
    while n > 1:
        print("Current value of n: {}".format(str(n)))
        result = result * n
        n = n - 1
    print("\nEnding condition met\n")
    return result
    
print(iterativeFactorial(5))

Calculating iterativeFactorial(5)

Current value of n: 5
Current value of n: 4
Current value of n: 3
Current value of n: 2

Ending condition met

120


## Performing Tasks More Quickly
### Consider Divide and Conquer
Divide and Conquer works by breaking down a problem into smaller problems until you find a problem that you can solve without too much trouble.

One example of applying this approach is the *binary search* algorithm, which finds the position of a target value in a sorted array. It does this by continously splitting the array in half and evaluating the midpoint split against the target value, and refining its search to the half which contains the target value.

In [93]:
def binarySearch(searchList, key):
    mid = int(len(searchList) / 2)
    print("\nMidpoint Index: {0}\tMidpoint Value: {1}".format(str(mid), str(searchList[mid])))
    
    if mid == 0:
        print("Key not Found!")
        return None
    elif key == searchList[mid]:
        print("Key Found!")
        return searchList[mid]
    elif key > searchList[mid]:
        newSearch = searchList[mid:len(searchList)]
        print("Key ({0}) is greater than midpoint ({1})".format(str(key), str(searchList[mid])))
        print("searchList now contains ", newSearch)
        binarySearch(newSearch, key)
    else:
        newSearch = searchList[0:mid]
        print("Key ({0}) is less than midpoint ({1})".format(str(key), str(searchList[mid])))
        print("searchList now contains ", newSearch)
        binarySearch(newSearch, key)

aList = list(range(1, 21))
binarySearch(aList, 5)


Midpoint Index: 10	Midpoint Value: 11
Key (5) is less than midpoint (11)
searchList now contains  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Midpoint Index: 5	Midpoint Value: 6
Key (5) is less than midpoint (6)
searchList now contains  [1, 2, 3, 4, 5]

Midpoint Index: 2	Midpoint Value: 3
Key (5) is greater than midpoint (3)
searchList now contains  [3, 4, 5]

Midpoint Index: 1	Midpoint Value: 4
Key (5) is greater than midpoint (4)
searchList now contains  [4, 5]

Midpoint Index: 1	Midpoint Value: 5
Key Found!
